CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./22.1.cpp -o 22.1.out
	$(CXX) -std=c++2a $(CFLAGS) ./22.2.cpp -o 22.2.out
	$(CXX) -std=c++2a $(CFLAGS) ./22.3.cpp -o 22.3.out
	$(CXX) -std=c++2a $(CFLAGS) ./22.3-7/22.3-7.cpp -o 22.3-7.out
	$(CXX) -std=c++2a $(CFLAGS) ./22.3-10/22.3-10.cpp -o 22.3-10.out
	$(CXX) -std=c++2a $(CFLAGS) ./22.3-12/22.3-12.cpp -o 22.3-12.out
	clear

clean:
	rm *.out