CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./6.2.cpp -o 6.2.out
	$(CXX) -std=c++2a $(CFLAGS) ./6.3.cpp -o 6.3.out
	$(CXX) -std=c++2a $(CFLAGS) ./6.4.cpp -o 6.4.out
	$(CXX) -std=c++2a $(CFLAGS) ./6.5.cpp -o 6.5.out
	clear

clean:
	rm *.out