CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./10.1.cpp -o 10.1.out
	$(CXX) -std=c++2a $(CFLAGS) ./10.2.cpp -o 10.2.out
	$(CXX) -std=c++2a $(CFLAGS) ./10.1-4/10.1-4.cpp -o 10.1-4.out
	clear

clean:
	rm *.out