CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./2.1.cpp -o 2.1.out
	$(CXX) -std=c++2a $(CFLAGS) ./2.2.cpp -o 2.2.out
	$(CXX) -std=c++2a $(CFLAGS) ./2.3.cpp -o 2.3.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/2-2.cpp -o 2-2.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/2-4.cpp -o 2-4.out
	clear

clean:
	rm *.out