CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./7.1.cpp -o 7.1.out
	$(CXX) -std=c++2a $(CFLAGS) ./7.3.cpp -o 7.3.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/7-1.cpp -o 7-1.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/7-2.cpp -o 7-2.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/7-4.cpp -o 7-4.out
	$(CXX) -std=c++2a $(CFLAGS) ./Problems/7-6.cpp -o 7-6.out
	clear

clean:
	rm *.out