CXX=g++
CFLAGS=-Wall
EXEC=run

run:
	$(CXX) -std=c++2a $(CFLAGS) ./12.1.cpp -o 12.1.out
	$(CXX) -std=c++2a $(CFLAGS) ./12.3.cpp -o 12.3.out
	$(CXX) -std=c++2a $(CFLAGS) ./12.3-5/12.3-5.cpp -o 12.3-5.out
	clear

clean:
	rm *.out